### ISSUE TITLE
Broke with Discord Update

### ISSUE THREAD

**Issue by thiaguinho4** [BleedingBD/plugin-RemoveChatButtons#8]
even with buttons active, the plugin doesn't work

**Comment by Jugom** [comment]
can confirm

**Comment by wilecoyote** [comment]
Gif and Gift button don't get removed. Still working with Emoji, Sticker and Attach button.

**Comment by QbDesu** [comment]
okay, while I cannot reproduce this myself could you guys please tell me (or better yet send a screenshot) of what the the `aria-label` says for those elements in the inspector? These `aria-label`s are what is used to identify and hide these particular buttons.

To do that you must first enable the dev tools in the BetterDiscord Settings:
![image](https://user-images.githubusercontent.com/5641607/228409792-2efbd5ed-8cbb-4176-8f53-88755e58ad95.png)

Then open the Dev Tools by pressing `Ctrl` + `Shift` + `i` (`Cmd` + `Shift` + `i` on Mac).
You should see a large panel pop-up on the side of your Discord client.
Click on the 3 dots next to the `x` and select dock to bottom (otherwise the dev tools are really hard to read)
![image](https://user-images.githubusercontent.com/5641607/228410759-907427ee-7a47-4cfe-8e69-af8a6231db12.png)

The panel should now be below the main Discord panel.
Now click the inspect button in the upper-left hand corner of the developer tools panel.
![image](https://user-images.githubusercontent.com/5641607/228411449-3aea2f77-0be6-46d7-9ebf-a1bc5a27d416.png)

Click right below the chat text box now, the whole text box should be marked for in blue when you do like in the following picture:
![image](https://user-images.githubusercontent.com/5641607/228411839-07cae3e3-28f7-4102-abb0-00af1117abd4.png)

In the developer tools there should now be a single element selected in the Elements tab. Right-click on that marked entry and click `Copy` -> `Copy outerHTML`.
![image](https://user-images.githubusercontent.com/5641607/228412481-64b0bff8-69f6-4a03-b680-3b29366eaf27.png)

There should now be some HTML in your clipboard, please paste that as a comment in here. (If you know how to put it in a code block if you don't that's fine, don't worry about it.)

**Comment by QbDesu** [comment]
that is unfortunately not not helpful, because this is is just the `svg` element for the image on the button. What I am asking for is the parent `button` element because it has the `aria-label` attribute I am looking for.

**Comment by wilecoyote** [comment]
> that is unfortunately not not helpful, because this is is just the `svg` element for the image on the button. What I am asking for is the parent `button` element because it has the `aria-label` attribute I am looking for.

I've updated the posting because of this. You now can see the complete button part of each button

**Comment by QbDesu** [comment]
thank you, hmm odd, seems like non-english languages borke, like in general. I'm gonna debug that tomorrow but yeah I can definitely recreate it by changing my client language to German now, so yeah, non-english-language support is borken at the moment.
